from __future__ import annotations

from typing import Any, Generic, Protocol, Self, TypeAlias, TypeVar, Union, runtime_checkable

from numpy.typing import DTypeLike, NDArray

from .index import Index

Array: TypeAlias = NDArray[Any]
TArray = TypeVar("TArray", bound=Array)
TScalar = TypeVar("TScalar")
Operand = Union["AbstractArrayProtocol[TArray, TScalar]", TArray, TScalar]
MatmulOperand = Union["AbstractArrayProtocol[Any, Any]", Array, float, int]
MatmulResult = Union["AbstractArrayProtocol[Any, Any]", Array, float, int]
IndexKey = Union[int, slice, tuple[Any, ...], Array]
SetValue = Union[TArray, TScalar]


@runtime_checkable
class AbstractArrayProtocol(Protocol, Generic[TArray, TScalar]):
    values: TArray

    def __array__(self, dtype: DTypeLike | None = None) -> Array: ...

    def __array_ufunc__(
        self, ufunc: Any, method: str, *inputs: Any, **kwargs: Any
    ) -> Any: ...

    def clone(self, **kwargs: Any) -> Self: ...

    def copy(self, **kwargs: Any) -> Self: ...

    def is_compatible_with(self, other: AbstractArrayProtocol[TArray, TScalar] | Index) -> bool: ...

    def check_or_assert(
        self, other: AbstractArrayProtocol[TArray, TScalar] | TArray | TScalar
    ) -> TArray | TScalar: ...

    def __add__(self, other: Operand) -> Self: ...

    def __radd__(self, other: Operand) -> Self: ...

    def __sub__(self, other: Operand) -> Self: ...

    def __rsub__(self, other: Operand) -> Self: ...

    def __mul__(self, other: Operand) -> Self: ...

    def __rmul__(self, other: Operand) -> Self: ...

    def __truediv__(self, other: Operand) -> Self: ...

    def __rtruediv__(self, other: Operand) -> Self: ...

    def __pow__(self, val: Union[int, float]) -> Self: ...

    def __iadd__(self, other: Operand) -> Self: ...

    def __isub__(self, other: Operand) -> Self: ...

    def __imul__(self, other: Operand) -> Self: ...

    def __itruediv__(self, other: Operand) -> Self: ...

    def __and__(self, other: Operand) -> Self: ...

    def __or__(self, other: Operand) -> Self: ...

    def __xor__(self, other: Operand) -> Self: ...

    def __iand__(self, other: Operand) -> Self: ...

    def __ior__(self, other: Operand) -> Self: ...

    def __ixor__(self, other: Operand) -> Self: ...

    def __lshift__(self, other: int) -> Self: ...

    def __rshift__(self, other: int) -> Self: ...

    def __ilshift__(self, other: int) -> Self: ...

    def __irshift__(self, other: int) -> Self: ...

    def __neg__(self) -> Self: ...

    def __abs__(self) -> Self: ...

    def __matmul__(self, other: MatmulOperand) -> MatmulResult: ...

    @property
    def shape(self) -> tuple[int, ...]: ...

    def __getitem__(self, key: IndexKey) -> Union[TArray, TScalar]: ...

    def __setitem__(self, key: IndexKey, item: SetValue) -> None: ...

    def __len__(self) -> int: ...
