from __future__ import annotations

import logging
from abc import abstractmethod
from .index import Index
from .. import Unit
from typing import Protocol, Self, Any, TypeAlias
from numpy.typing import NDArray, DTypeLike
#from nptyping import NDArray, Floating, Shape

LOG = logging.getLogger(__name__)
logging.captureWarnings(True)

#TODO Implement all of the i-methods and logical methods
# [ ] __imatmul__

Array: TypeAlias = NDArray[Any]

class AbstractArrayProtocol(Protocol):
    __default_unit: Unit
    #values: NDArray[Shape['*', ...], Floating]
    values: Array

    def __init__(self, values: Array): ...

    @property
    def __array_interface__(self): ...

    def __array__(self, dtype: DTypeLike | None = None) -> Array: ...

    def __array_ufunc__(self, ufunc: Any, method: Any, *inputs: Any, **kwargs: Any) -> Array: ...

    @abstractmethod
    def is_compatible_with(self, other: AbstractArrayProtocol | Index) -> bool: ...

    @abstractmethod
    def clone(self, **kwargs: Any) -> Self: ...

    def copy(self, **kwargs: Any) -> Self: ...

    def check_or_assert(self, other: AbstractArrayProtocol | Array | float) -> Array | float: ...

    def __sub__(self, other: AbstractArrayProtocol | Array | float) -> Self: ...

    def __rsub__(self, other: AbstractArrayProtocol | Array | float) -> Self: ...

    def __add__(self, other: AbstractArrayProtocol | Array | float) -> Self: ...

    def __radd__(self, other: AbstractArrayProtocol | Array | float) -> Self: ...

    def __mul__(self, other: AbstractArrayProtocol | Array | float) -> Self: ...

    def __rmul__(self, other: AbstractArrayProtocol | Array | float) -> Self: ...

    def __truediv__(self, other: AbstractArrayProtocol | Array | float) -> Self: ...

    def __rtruediv__(self, other: AbstractArrayProtocol | Array | float) -> Self: ...

    def __pow__(self, val: float) -> Self: ...

    def __iand__(self, other: AbstractArrayProtocol | Array | float) -> Self: ...

    def __and__(self, other: AbstractArrayProtocol | Array | float) -> Self: ...

    def __or__(self, other: AbstractArrayProtocol | Array | float) -> Self: ...

    def __ior__(self, other: AbstractArrayProtocol | Array | float) -> Self: ...

    def __ixor__(self, other: AbstractArrayProtocol | Array | float) -> Self: ...

    def __xor__(self, other: AbstractArrayProtocol | Array | float) -> Self: ...

    def __lshift__(self, other: AbstractArrayProtocol | Array | float) -> Self: ...

    def __rshift__(self, other: AbstractArrayProtocol | Array | float) -> Self: ...

    def __ilshift__(self, other: AbstractArrayProtocol | Array | float) -> Self: ...

    def __irshift__(self, other: AbstractArrayProtocol | Array | float) -> Self: ...

    def __iadd__(self, other: AbstractArrayProtocol | Array | float) -> Self: ...

    def __isub__(self, other: AbstractArrayProtocol | Array | float) -> Self: ...

    def __imul__(self, other: AbstractArrayProtocol | Array | float) -> Self: ...

    def __itruediv__(self, other: AbstractArrayProtocol | Array | float) -> Self: ...

    def __invert__(self) -> Self: ...

    @abstractmethod
    def __matmul__(self, other: AbstractArrayProtocol | Array | float) -> Self: ...

    #def __rmatmul__(self, other) -> AbstractArrayProtocol:

    @property
    def shape(self) -> tuple[int, ...]: ...

    def __getitem__(self, key: Any) -> Self: ...

    def __setitem__(self, key: Any, item: Any) -> Self: ...

    def __getattr__(self, attr: str) -> Any: ...

    def __len__(self) -> int: ...

    def __neg__(self) -> Self: ...

    def __lt__(self, other: AbstractArrayProtocol | Array | float) -> Self: ...

    def __gt__(self, other: AbstractArrayProtocol | Array | float) -> Self: ...

    def __le__(self, other: AbstractArrayProtocol | Array | float) -> Self: ...

    def __ge__(self, other: AbstractArrayProtocol | Array | float) -> Self  : ...

    def __abs__(self) -> Self: ...

    @property
    def vlabel(self) -> str: ...

    @property
    def valias(self) -> str: ...

    @property
    def name(self) -> str: ...

    @name.setter
    def name(self, name: str): ...
