name: main


# Automatically cancel a previous run.
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true


on:
  push:
    branches:
      - workflow # For debugging the workflow..
      - main
    pull_request:
      - '*'
#on:  
#  push:
#  pull_request:
#    branches:
#      - master
#  release:
#    types: [published]

jobs:

  build_wheel:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['macos-latest']
    steps:
      - uses: actions/checkout@v3

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.12.0
        env:
          CIBW_ARCHS_MACOS: x86_64 arm64

  #test_wheel:
  #  name: Test wheel on ${{ matrix.os }}
  #  runs-on: ${{ matrix.os }}
  #  strategy:

