name: main


# Automatically cancel a previous run.
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true


on:
  push:
    branches:
      - workflow # For debugging the workflow..
      - main
    pull_request:
      - '*'

jobs:

  build_wheels:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
    steps:
      - uses: actions/checkout@v3

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.12.0
        env:
          CIBW_BUILD: cp310-manylinux_x86_64

      - name: Install wheel
        run: |
          ls -las wheelhouse
          pip install wheelhouse/OMpy-1.1.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl

      #- uses: actions/upload-artifact@v3
      #  with:
      #    path: dist/*.tar.gz
      #- name: Install python
      #  uses: actions/setup-python@v4
      #  with:
      #    python-version: "3.10"


  #test_wheel:
  #  name: Test wheel on ${{ matrix.os }}
  #  runs-on: ${{ matrix.os }}
  #  strategy:

