name: main


# Automatically cancel a previous run.
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true


on:
  push:
    branches:
      - workflow # For debugging the workflow..
    pull_request:
      - '*'

jobs:

  tests-ubuntu:
    name: Run tests for ${{ matrix.os }} on ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}


    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
        python-version: ['3.8', '3.9', '3.10']


    steps:
      - uses: actions/checkout@v3
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
    
      - name: Install build essentials
        run: sudo apt install gfortran cmake liblapack-dev libblas-dev libomp-dev libopenmpi-dev
      - name: Download and install multinest
        run: |
          git clone https://github.com/JohannesBuchner/MultiNest
          cd MultiNest/build
          cmake ..
          make
        env:
          FC: /usr/local/bin/gfortran-11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
      - name: Install OMpy
        run: pip install -e .
      - name: Run tests
        run: pytest --cov
        env:
          LD_LIBRARY_PATH: /home/runner/work/ompy/ompy/MultiNest/lib
      #- name: Upload coverage report.

  tests-macos:
    name: Run tests for ${{ matrix.os }} on ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}


    strategy:
      fail-fast: false
      matrix:
        os: ['macos-latest']
        python-version: ['3.8', '3.9', '3.10']


    steps:
      - uses: actions/checkout@v3
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
    
      - name: Install build essentials
        run: brew install cmake gcc libomp gfortran
      - name: Download and install multinest
        run: |
          git clone https://github.com/JohannesBuchner/MultiNest
          cd MultiNest/build
          cmake ..
          make
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
      - name: Install OMpy
        run: pip install -e .
      - name: Run tests
        run: pytest
        env:
          LD_LIBRARY_PATH: /home/runner/work/ompy/ompy/MultiNest/lib
