name: main


# Automatically cancel a previous run.
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true


on:
  push:
    branches:
      - workflow # For debugging the workflow..
      - main
    pull_request:
      - '*'

jobs:

  build_wheels:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
    steps:
      - uses: actions/checkout@v3

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.12.0
        env:
          LD_LIBRARY_PATH: /home/runner/work/ompy/ompy/MultiNest/lib
          CIBW_BUILD: cp310-manylinux_x86_64
          CIBW_TEST_COMMAND: pytest {project}/tests
          CIBW_BEFORE_TEST_LINUX: >
            git clone https://github.com/JohannesBuchner/MultiNest &&
            cd MultiNest/build &&
            cmake ..&&
            make
          CIBW_TEST_REQUIRES: pytest pytest-cov


  #test_wheel:
  #  name: Test wheel on ${{ matrix.os }}
  #  runs-on: ${{ matrix.os }}
  #  strategy:

