name: main


# Automatically cancel a previous run.
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true


on:
  push:
    branches:
      - workflow # For debugging the workflow..
      - main
    pull_request:
      - '*'

jobs:

  build_wheels:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
    steps:
      - uses: actions/checkout@v3

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.12.0


  #test_wheel:
  #  name: Test wheel on ${{ matrix.os }}
  #  runs-on: ${{ matrix.os }}
  #  strategy:

